name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.3'  # Pastikan ini adalah versi Go yang valid
      - name: Run update script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: go run main.go
      - name: Commit and Push changes
        run: |
          git config --global user.name 'gilang swandaru'
          git config --global user.email 'gilangswandaru27@gmail.com'
          git add README.md
          git commit -m "Update README with latest news"
          git push
